#!/bin/sh

mount -t proc proc /proc
mount -t sysfs sys /sys
mount -t devtmpfs dev /dev
mkdir /dev/pts
mount -t devpts devpts /dev/pts

insmod /ldi_bus.ko
insmod /ldi_device.ko

ifconfig eth0 192.168.2.2
ifconfig lo 127.0.0.1

/bin/telnetd 
